[package]
name = "Celeritas"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8", features = [ "runtime-tokio" ] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
actix-web = "4"
serde = "1"
